### ISSUE TITLE
Consider a more permissive license

### ISSUE THREAD

**Issue by throwaway1973** [fantasylandinst/fcop#11]
Amazing project. A true "GPL for civility" in all senses of that phrase. However, due to licensing concerns I'm unable to recommend it to friends for actual use rather than just as an example of legalistic poetry.

https://github.com/fantasylandinst/fcop/blob/master/COC.md states at the top: "Copyright © 2016 Fantasyland Institute of Learning. All Rights Reserved."

Contrast with (for example) the Django code of conduct (https://www.djangoproject.com/conduct/reporting/) which is licensed under creative commons. I would recommend their choice (CC BY), though of course the decision is yours.

Regardless of your licensing decision, thank you for posting this. You made my day!

**Comment by throwaway1973** [comment]
Separate issue bordering on trivial: consider renaming the "Private Communication" subsection of "Privacy" to "Semi-Private Communication" (as that is the sole topic discussed in the subsection).

The above feels too small to open another ticket, so I'll just leave the thought here.

**Comment by jdegoes** [comment]
@throwaway1973 Thanks for the feedback on this and the other issues, and the pull requests. I or Morgan will respond over the coming days.

On this issue, our sole concerns are that the license not be called "FCOP" if has been tweaked; and that it not be, e.g., defaced and attributed to FIOL.

Any feedback on the above?

**Comment by throwaway1973** [comment]
> our sole concerns are that the license not be called "FCOP" if has been tweaked; and that it not be, e.g., defaced and attributed to FIOL

This is in the normal use case for CC BY. From the license (https://creativecommons.org/licenses/by/4.0/):

> Attribution — You must give appropriate credit, provide a link to the license, **and indicate if changes were made.** You may do so in any reasonable manner, **but not in any way that suggests the licensor endorses you or your use.** [emphasis mine]

This of course would not prevent a defaced version from being created and attributed to FIOL, but it would mean such versions would be unlicensed, and that the FIOL would have solid legal grounds for a removal request.

(The above is me restating my understanding from having read the creativecommons website, I'm not a lawyer, etc. I would also put this disclaimer if describing other open source licenses such as the GPL or MIT licenses. The gory non-summary details of the license can be viewed at https://creativecommons.org/licenses/by/4.0/legalcode)

If you have other desires with respect to license terms, or are interested in what other license restrictions are commonly used, https://creativecommons.org/licenses/ and/or https://wiki.creativecommons.org/wiki/License_Versions would probably be worth a quick skim. Non commercial use only, and explicitly disallowing derivative works are among the license flavors available there for free.

**Comment by throwaway1973** [comment]
Again I'm not a lawyer, but I googled for a bit, and it looks like FCOP would need to be trademarked if you want to prevent people from using the term in the general case [assuming you're worried about completely original codes of professionalism being referred to as FCOP as well as derivative works]

**Comment by throwaway1973** [comment]
Okay, having had some time to think about it, I believe the following things:

1. The question of FCOP and FIOL name usage seems to be the general issue of trademarks. In theory you *may* be able to solve this via additional license terms, however solving it the more usual way seems preferable if you anticipate needing to use traditional legal methods of enforcement. You don't want to be the test case for clever code, etc. I am not an expert in this area, so this should be checked.

2. The more I think about it, the more I like the idea of the FCOP being analogous to a standardized constitution and legal system, onto which end users can add their own additional rules (or libraries as the case may be). A sort of software-framework-style solution for project politics as I mentioned in https://github.com/fantasylandinst/fcop/issues/31.

If this is of interest, I recommend using the same license as the GPL with only minor modification: ("Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed **except changes for the purpose of creating github pull requests to this project**.") Which solves the immediate copyright issues and leaves things flexible going forward. Again though, I'm not a lawyer so this would need to be checked.

**Comment by jdegoes** [comment]
Something like:

> This work is licensed under CC BY-ND 4.0, with an exception for derivative works that are exclusively created for and distributed as pull requests to this repository.
