### ISSUE TITLE
Perhaps clarification could me made as to the intent of non-victimized reporting?

### ISSUE THREAD

**Issue by throwaway1973** [fantasylandinst/fcop#17]
Sorry if I'm opening too many issues. I'm very excited by this project as a sort of keystone for civil communities, and so I'm trying to polish it as much possible from my limited perspective.

Under Violations it is stated that "If you are a victim but you do not feel victimized, you may choose to not report the violation. In this case, we will not treat the incident as a violation." which seems nicely put. However, I am curious what use cases you were expecting that would necessitate supporting a victim who does not feel victimized. To my reading the simplest case would be related to "Active participation violations ... may not be reported by third-parties" (so using what you can report as a substitute good for not being able to report a separate violation as a 3rd party). Another possible use case would be reporting as a substitute good for 1st party behavior not in violation of the FCOP.

I personally feel like both of the above use cases go against something important but currently implicit, and that making it explicit would improve the document.

Suggested fix: a section could be added to the Active Participation section along the lines of "Don't Go Vigilante. If you believe that some behavior not in violation of the FCOP should be punished, or that some past decision by an FCOP judge was made in error, please do not take justice into your own hands. Instead, open dialogue with the FCOP about these feelings directly."

I am somewhat unhappy with that wording, but I feel like it ties together a lot of the other sections by making their reasoning more explicit. Thoughts?

**Comment by jdegoes** [comment]
I am not sure about this one. I like the idea, but what forms of "going vigilante" are currently permissible? If one chooses to leave the community, then one can do anything (not forbidden by separate agreements). If one chooses to stay, one must not endanger the career of members, share private details, or name & shame them. Is there something missed by these protections?

**Comment by throwaway1973** [comment]
My apologies for the above wording. I was meaning to discuss both:

> Alice reports Bob for a perceived violation of the FCOP. The arbiter rules in Bob's favor. Alice does not like the result, so Alice reports Bob for a separate violation of the FCOP for which she doesn't feel victimized.

> Alice reports Bob for a perceived violation of the FCOP. The arbiter rules in Bob's favor. Carol does not like the result, so Carol reports Bob for a separate violation of the FCOP for which she doesn't feel victimized.

Both of which feel like vigilante justice (since they are related to not accepting an FCOP ruling). Looking at this now, I feel like addressing this point would likely needlessly complicate the FCOP -- the arbiter would presumably catch this if it's an issue.

**Comment by jdegoes** [comment]
👍 I agree the arbiter can handle these cases. Closing this issue for now.
