### ISSUE TITLE
Clarify "judgmental communication"

### ISSUE THREAD

**Issue by jdegoes** [fantasylandinst/fcop#25]
In particular, make it clear that a subjectively stated "best for purpose X" is not a judgmental communication, and include examples of things that do not qualify as judgmental communication because they refer to objectively measurable metrics.

**Comment by throwaway1973** [comment]
Very much agree. This is quite related to my floundering around with wording over in https://github.com/fantasylandinst/fcop/issues/12

**Comment by jdegoes** [comment]
I will close this in favor of #12.
