### ISSUE TITLE
Slight tweak to harassment

### ISSUE THREAD

**Issue by jdegoes** [fantasylandinst/fcop#26]
Harassment is defined as follows:

> We define harassment as an attempt to interact with someone who does not consent to the interaction.

Make sure "interact" refers to _interaction_ as defined in the glossary so it is clear it refers to the various forms of interaction.

**Comment by throwaway1973** [comment]
Perhaps, throughout the document, references to defined terms could be somehow marked?

**Comment by jcsalomon** [comment]
@throwaway1973, that’s what the _italics_ everywhere are for.

**Comment by throwaway1973** [comment]
@jcsalomon I feel silly now. Thanks for pointing that out.
