### ISSUE TITLE
"Don't Shame" Possibly inverted.

### ISSUE THREAD

**Issue by bshelden** [fantasylandinst/fcop#3]
Don't Shame. You must not discuss a member's behavior in the Community outside the Community, without express permission.

My read of that suggests it's intended to keep secret what happens in the Community.  Did you mean this the other way?  That is "leave what is outside outside".

**Comment by jdegoes** [comment]
It's both. To feel safe, people need to feel like behavior that occurs in a community won't be broadcast to the world.
