### ISSUE TITLE
Consider expanding what constitutes a protected class.

### ISSUE THREAD

**Issue by throwaway1973** [fantasylandinst/fcop#30]
From the Welcome Statement: "civil people of all genders, gender-expressions, sexual-orientations, gender-orientations, races, ethnic origins, skin colors, physical disabilities, intellectual disabilities, ages, sizes, political views, religious views, philosophies, beliefs, and attitudes."

I very much like this list, and feel it could be expanded. For example, I have a very vivid memory of a person who dropped out of a Physics PhD program to become a data scientist. The manner in which he was worried about being judged an outsider, despite his clear aptitude, reminds me in some sense of the judgement apprehension I associate with members of the above protected classes.

I guess I'm saying I believe current and past professions should also go on the list. If someone is attending a functional programming conference and currently codes in C++, I don't think they should be treated differently. Double that for someone currently working as a chef, gas station attendant, or physicist. If the aptitude is there, the interest is there, and they're putting in the work, then they should be welcome in the community.

(Note that I guess I'm okay with making inferences based on experience level, I just don't think it's psychologically helpful when someone's current profession is the basis for inferring their experience level. "You're a student, you'll understand once you've been in industry for a few years" is awful in much the same way that a sexist remark is awful, in my opinion. (I'm not trying to diminish sexist remarks by that statement. Those are also awful.))

The same goes for past and current country of residence.

I wish we could figure out what the common feature is of things that should be on this list. I'm sure there are several important categories that we're currently missing. Maybe it's just categories which are orthogonal to the group's purpose? I'm worried that stating it that way will not be as calming to someone who's suffering from judgement apprehension.

**Comment by jdegoes** [comment]
Yes, I think ultimately, it boils down to, "categories orthogonal to the professional goals of the community". We probably need a slight expansion of the list but also to make it clear these are examples of categories orthogonal to the professional goals of the community—such that if we leave a group off the list, it is not taken as an indication that said group is unwelcome from participation.

**Comment by throwaway1973** [comment]
Okay, revisiting this I guess I do actually like adding "orthogonal characteristics" to the defined terms section, with the welcome message at the top serving to help people feel comfortable.

**Comment by jcsalomon** [comment]
@jdegoes said,
>  … make it clear these are examples of categories orthogonal to the professional goals of the community—such that if we leave a group off the list, it is not taken as an indication that said group is unwelcome from participation.

A risky but plausible way to achieve this would be to leave off the list of examples the three or four most obvious entries.

**Comment by wilx** [comment]
This is getting ridiculous...
