### ISSUE TITLE
Consider adding meta-rules to the FCOP

### ISSUE THREAD

**Issue by throwaway1973** [fantasylandinst/fcop#31]
I'm slowly working through the project founder's blog, and keep being surprised at the level of insight and clear thinking that's displayed with respect to the problems the FCOP seems well suited for dealing with. http://degoes.net/articles/lambdaconf-conclusion for example says:

> social media is fickle, highly emotional, and irrational; and it distorts or ignores the truth in exchange for more likes and retweets... After much reflection, we have decided that we will **adopt a policy that prevents us from making policy changes solely in response to social media, with a mandatory cool-off period**...  For people who want to contribute... We ask that you be kind, and use science, data, and thoughtful arguments that avoid logical fallacies. [emphasis added]

It's probably too early to start putting them in place, but perhaps some guidance and policies which govern the behavior of arbitors, and govern edits to the FCOP itself, would be a good idea. This may seem like overkill for the FIOL's specific situation, and I do not know if it is in scope for the project, but I view meta-rules of these kind as potentially allowing (some hypothetical project founder who adopts the FCOP) to keep just a little more sanity in place during a social media onslaught. "Sorry, please see the FCOP for why we can't respond for the next x days. If you are curious why this policy exists, please see http://Y" or similar.

If the FCOP is interested in supporting use cases like the above, perhaps you will be interested in generalizing further. It is interesting to consider if the FCOP could act as something akin to the US Constitution for projects and conferences. Rather than having each community edit the FCOP to suit its needs, the community would adopt the FCOP, and then create the equivalent of federal law to augment the core governance provided by the FCOP. Removing the need for user edits is quite related to the licensing discussion found in https://github.com/fantasylandinst/fcop/issues/11 and would work well with the transitive clause suggested at https://github.com/fantasylandinst/fcop/issues/29.

(I also suspect you are in some sense already doing this with respect to keeping lambdaconf specific rules out of the FCOP. Perhaps something like the above is why?)

**Comment by jdegoes** [comment]
I agree that meta-rules governing FCOP's evolution would be useful, and could incorporate guiding principles of FCOP, such as, "No influence by social media," "Only governing external behavior," etc.

**Comment by jdegoes** [comment]
* Policies may not be influenced by social media (w/mandatory cool down).
 * Policies may only dictate behavior, not thought or other internal characteristics.
 * Policies may not promote any agenda other than the professional goals of the community [and as a component of this, continued participation in professional life for members].
 * Policies must protect against corrupt FCOP communities.
