### ISSUE TITLE
Clarify maximum consequence

### ISSUE THREAD

**Issue by jdegoes** [fantasylandinst/fcop#32]
Something along the lines of:

> In no case will the consequence for violating FCOP exceed banishment (excluding criminal offenses).

This could help shield victims within a corrupt FCOP community from legal action should they choose to go vigilante.

**Comment by throwaway1973** [comment]
Maybe pedantic, but an FCOP community with employees may want to let one go for violating the FCOP.

Also reporting the banishment would be necessary for https://github.com/fantasylandinst/fcop/issues/29

Perhaps:

> In no case will the consequence for violating the FCOP exceed banishment and reporting of the banishment, unless the violation is also governed by a separate contractual agreement or local law.

**Comment by jdegoes** [comment]
Good idea.
