### ISSUE TITLE
Change nomenclature around violations

### ISSUE THREAD

**Issue by ankushnarula** [fantasylandinst/fcop#34]
The current language defines members as "_victims_" and "_violators_" with or without a conclusive finding by the arbiter.  Consider that as it stands, the FCOP is describing a process without making state changes.  

**Summary**

`Member -> Aggrieved -> Complainant -> Victim`

`Member -> Accused -> Respondent -> Violator`

**Detail**

1. A member who believes they have been wronged by a violation is an "_Aggrieved_" member
2. A member attributed with a violation is an "_Accused_" member
3. An _aggrieved_ member who wishes to seeks official intervention is a "_Complainant_" 
4. An arbiter decides if there is enough evidence whether the  _accused_  member must answer as a "_Respondent_"
5. The arbiter investigates until a settlement is reached or the arbiter has issued a judgement
6. A _respondent_ who is judged to have violated the code is a "_Violator_" 
7. A _complainant_ who is judged to have been wronged is a "_Victim_"

**Recommendation**

Use "_Aggrieved_" and "_Accused_" for the sake of simplicity.  Retain _violator_ to emphasize when a judgement has been rendered and a member's status has changed. This removes implied assumptions from the existing nomenclature.  Any status beyond these two can be used for administrative purposes.

**Comment by jdegoes** [comment]
👍 Excellent suggestion. I was thinking about this issue the other day.

**Comment by ankushnarula** [comment]
I'm not 100% on my own writing at the moment.  Apologies for any inattention to detail.
