### ISSUE TITLE
Counterbalance Behavioral Constraints with Guiding Principles

### ISSUE THREAD

**Issue by ankushnarula** [fantasylandinst/fcop#36]
This thought emerged in reaction to the "Don't..." and "No..." language around "[judgemental communications](https://github.com/fantasylandinst/fcop/issues/12)".

In principle it makes sense to constrain language and communication.  In practice, I foresee see such constraints leading to a minefield of unnatural communications and misunderstandings.  For me, the definitions that constrain behavior put my mind in a neurotic and defensive mode -  especially when I contemplate adherence to the code in all situations.  

Perhaps it could be beneficial to counterbalance constraints with an elaboration of "Do's" that propel virtuous conduct; call them "driving principles" rather than "guiding principles".  For example,  the "_Assume the Best_" section asks the reader to be open, empathetic, and creative when listening to others.  This kind of language "drives discourse forward" rather than only "keeping it between the lines".

I recently came across two other more formal concepts of positive and productive discourse:  "[Steelmanning](https://wiki.lesswrong.com/wiki/Steel_man)" and "[The Principle of Charity](http://philosophy.lander.edu/oriental/charity.html)".   I'm sure there are other such principles and concepts to draw upon for inspiration but I think these will cover a vast array of real-world situations.

**Comment by jdegoes** [comment]
@ankushnarula Have you seen the scaled back suggestions in the comments of #12?

I have similar thoughts on "Do's", for example on being polite, etc. I am not sure whether these would be a strict requirement (how do you measure and enforce "be open" or "be empathic", for example? And what of people who are closed by nature, or autistic, for example?), or if they would be stated as encouragement / exhortation.

Perhaps an exhortation along the following lines:

> "We encourage everyone to assume the best in any interaction; to be open, honest, empathic, and creative in communication; and to demonstrate politeness and professional courtesy."

Then the list can be trimmed strictly into a narrowed group of "Don'ts", which would all be items that are relatively easy to measure and enforce. (The existing "Assume the best" is neither easy to measure nor to enforce.)

What do you think about this approach? 

I'll read the two references tomorrow.
