### ISSUE TITLE
Broaden "peaceful" to "civil"

### ISSUE THREAD

**Issue by jdegoes** [fantasylandinst/fcop#4]
Peaceful (law-abiding) is not sufficient: imagine people trying to disrupt each other (shouting, blow horns), etc. There are a range of categories detrimental to a professional environment not covered by the laws of the land. The focus should be on civility, but figuring out how to describe that is another matter.

**Comment by LeFey** [comment]
IMO peaceful is still good. It sounds like what we want to avoid here are attempts at "no platforming." To do that we can just specify that speakers must not be interrupted during talks or blocked from physically entering conference areas.

**Comment by jdegoes** [comment]
Agreed, and figure out what the equivalent is for online communities like Github (e.g. spamming an issue with bots, trying to delete issues or overwrite wiki information maliciously, or spamming a repo with useless PRs, etc.).

**Comment by ankushnarula** [comment]
Is it useful to broaden the scope of bad behavior and sabotage?  Specifically, ill-intentioned reasons such as competition and mischief?  It could be as simple as appending the opening of the Statement of Purpose:

> The Fantasyland Institute of Learning Code of Professionalism (FCOP) dictates the terms and conditions under which we allow you to participate in the community _**in good faith**_.

And this could be emphasised by expanding the definition of _civil_:

> **Civil.** We define civil individuals as _**well intentioned**_ individuals who [...]

Because this is not a legal contract, it might be useful to emphasize that participant behavior is fundamentally evaluated under such a standard.

**Comment by jdegoes** [comment]
> Specifically, ill-intentioned reasons such as competition and mischief?

There are two issues I see with this:

1. Some people object to COCs on grounds they use "weasel words" that allow people to kick out anyone they don't like (for any reason at all, really). It could be argued that "well-intentioned" is a weasel phrase that supports anyone being banned for any arbitrary reason, on grounds their intentions are not "well".
2. Currently FCOP is strongly concerned with behaviors and totally unconcerned with intentions. Stated differently, if someone who is ill-intentioned does not behave in a manner consistent with FCOP, they would still be welcome if we are consistent with other policies (e.g. they can believe whatever they think, they can judge people however they want — albeit only non-verbally — and so forth).

That said, I do like the idea, and think we should make sure we
