### ISSUE TITLE
Requiring victims to request resolution is harmful

### ISSUE THREAD

**Issue by mjg59** [fantasylandinst/fcop#44]
If a member publicly breaches the code and then threatens the victim into not requesting resolution, there is no mechanism for taking action against the violator

**Comment by jdegoes** [comment]
👍 I think this warrants further discussion.

**Comment by ankushnarula** [comment]
As it's written, the "No Victimless Violations" section assumes that individuals are self-policing.  In a scenario such as in the OP, perhaps the aggrieved party could report through a trusted third-party but ultimately would need to file the complaint themselves. This would ensure authenticity of the claim and the safety of the aggrieved party.

**Comment by jdegoes** [comment]
@ankushnarula Perhaps allow reports through third-parties but require they be authenticated?

Or perhaps this falls outside the scope of FCOP, since threatening individuals is a crime and therefore must be handled by the legal system (perhaps with facilitation of community leaders).

**Comment by ankushnarula** [comment]
I think you're generally correct unless such a threat is not covered by law but involves another breach - like the threat of doxxing or exposing private information.

**Comment by jdegoes** [comment]
> I think you're generally correct unless such a threat is not covered by law but involves another breach - like the threat of doxxing or exposing private information.

Then it seems like a suitable middle-ground might be: authenticated third-party reports are allowed in cases where aggrieved members are reportedly being threatened by breach of privacy.

Needs more thought & discussion but seems like it could be useful. My one concern is that if you are being threatened and a third-party reports it, ultimately the person doing the threatening will find out that someone snitched, and after being banned by the community, has no further incentive to avoid doxxing.

**Comment by jdegoes** [comment]
Superseded by #58
