### ISSUE TITLE
Please ban me from any involvement for "moralizing"

### ISSUE THREAD

**Issue by EvanBurchard** [fantasylandinst/fcop#47]
Let me know if I need to go further.

"Nazis are bad." Will that do it?

**Comment by ankushnarula** [comment]
> **No Victimless Violations**. If you are aggrieved, you may choose to not seek resolution for the incident. In this case, we will not treat the incident as a violation.

Nothing - unless it affects a member and that aggrieved member files a complaint. After the aggrieved member files a complaint, there is an arbitrated process for complaint review, remediation, and punishment.

The purpose of "No Moralizing" is to curtail the escalation of moral superiority conflicts between diverse viewpoints in order to enhance a free flow of dialogue in the community.  It is easy to imagine sub-groups forming within the community based on religious, political, economic, and social preferences rather than on professional interests and intellectual curiosity.  

Rather than devolve into flame wars based on battling factions of moral preferences, the "No Moralizing" clause asks members to expose each other's views to intellectual scrutiny as individuals. However, people are fallible and will falter from time to time. Thus, some [first principles of rational discourse](http://evolvingthoughts.net/2009/06/a-code-of-conduct-for-effective-rational-discussion/) should apply - particularly [the principle of charity](http://evolvingthoughts.net/2009/06/a-code-of-conduct-for-effective-rational-discussion/#toc-the-principle-of-charity).

**Comment by EvanBurchard** [comment]
Ok. FCOP authors have a terrible moral worldview (worse than mine) because the policies of FCOP create a community that is welcoming to nazis (who are bad). 

Anyone aggrieved yet?

**Comment by ankushnarula** [comment]
> the policies of FCOP create a community that is welcoming to nazis

Wrong.  The policies of the FCOP prevent Nazi and all other hate speech and harmful behavior.  Please demonstrate otherwise or retract your claim.

**Comment by EvanBurchard** [comment]
Demonstration is on its way... give me some time.

**Comment by adrienne** [comment]
> Wrong. The policies of the FCOP prevent Nazi hate speech and all other hate speech and harmful behavior. Please demonstrate otherwise or retract your claim.

He doesn't have to prove his claim; he has explicitly moralized and therefore, by the completely ridiculous rules of the FCOP, he must be punished.

**Comment by EvanBurchard** [comment]
@adrienne I apparently didn't aggrieve anyone yet, but I think I will soon.

**Comment by EvanBurchard** [comment]
> Wrong. The policies of the FCOP prevent Nazi hate speech and all other hate speech and harmful behavior. Please demonstrate otherwise or retract your claim.

I'm not sure how to demonstrate. I don't have any nazi friends who I can ask if they'd feel welcome at an FCOP event or not. Maybe you do?

I don't think there's evidence I can give that you would believe. 

But I'll try. Let's say there are 3 types of possible attendees: 

1. People who won't go because of this alt-right nonsense that you guys allow (doesn't matter if it happens at the event itself. People still won't go because of it)
2. People who don't care or feel that the distinction of (active/inactive, or private/professional) is important, adequate, whatever. They don't care.
3. People who will go because of this alt-right nonsense that you guys allow (doesn't matter if it happens at the event itself. People still will go because of it)

If you deny group 1 exists, I can find plenty of examples (including me). Group 2 obviously exists and is quite possibly, the largest*. Do you think group 3 doesn't exist? 

\* The largest for now. Group 3 might get really excited at some point and be your whole community.

Incidentally, I wrote a bit about how stupid it is to head this direction instead of just taking the initial bug report:
http://blog.evanburchard.com/nazis-cocs-and-testing/

**Comment by jdegoes** [comment]
I'm going to close this as non-constructive and off-topic. If you'd like to contribute to the project, please submit non-moral critiques and / or pull-requests.

**Comment by EvanBurchard** [comment]
@jdegoes I don't understand how this project isn't meant as the document intended to define the morality of the community and associated events.

**Comment by adrienne** [comment]
@EvanBurchard - @jdegoes clearly believes that a document can be written like this, to define a community's parameters, without being a *moral* document. This is self-evidently nonsense, but it does seem to be what is going on.

**Comment by EvanBurchard** [comment]
@adrienne I mean... I think legal frameworks, CoCs, etc. all kind of fall under "normative ethics." Gets pretty mashed together I think. I don't know. Hopefully he comes around. I like haskell, but not enough to surround myself with the group 3 types (group 4 in my blog post).

**Comment by EvanBurchard** [comment]
@adrienne I'm starting to believe this isn't true "clearly believes that a document can be written like this, to define a community's parameters, without being a moral document."

I elaborate a bit [here](https://github.com/fantasylandinst/fcop/issues/66), but at this point, I'm not really convinced. Sorry for dragging you back in. Seems like either, yeah, this is nonsense, or he's a seriously bad person being disingenuous and intentionally creating the kind of nazi-friendly community that is whoopsy maybe sorta supported by some shaky meta-ethical philosophical framework that he's grasping at, rather than actually holding dear. Or this project is mostly bait, to waste our time? which I guess would put him... uhh. In the middle somewhere?

I don't know. Maybe he doesn't know either. It's just really hard to believe at this point that NVC or emotivism as foundational methods of communication aren't acting as a placeholder for "whatever I say cause I'm the king."
