### ISSUE TITLE
A moral framework that doesn't allow moral critiques is confusing

### ISSUE THREAD

**Issue by EvanBurchard** [fantasylandinst/fcop#49]
Please explain how that works. Is it like "meta-ethics" or something?

**Comment by jdegoes** [comment]
@EvanBurchard FCOP is not a moral framework. It is a set of terms and conditions for participation. It does not claim these terms and conditions are morally superior to any other. It merely states if you wish to participate, you must abide by the terms and conditions, as well as lays out what can happen if you do not. FCOP has no opinion on the morality of its terms and conditions and such a question is out of scope for the FCOP community.
