### ISSUE TITLE
Use of the word "victim"

### ISSUE THREAD

**Issue by EvanBurchard** [fantasylandinst/fcop#50]
https://en.wikipedia.org/wiki/Victim_feminism

Honestly, there are a ton of people who are actually skilled and trained in social work, gender studies, inclusive design, queer studies, psychotherapy, etc. People-studies stuff.

Get their help? 

The basics are getting screwed up here, and I'm not the one who can explain it the best. Please get the help of people who don't think like you, or the people who think like you will be all you can attract. If you don't see that as a limitation, I don't know what to tell you.

**Comment by jdegoes** [comment]
Lots of people would create a different COC if given the opportunity. Indeed, many have—there is a multitude of choices these days. 

If you want to persuade us to adopt some change to FCOP, you will have to appeal to the goals of FCOP (which are not your goals), show how research, data, or experience (worst case) suggests the goals will not be satisfied by the current terms and conditions.

**Comment by EvanBurchard** [comment]
@jdegoes Nah. I think I'm done. You do you, boo.
