### ISSUE TITLE
"Moralizing" is a required element of enforcing any code of conduct; forbidding it prevents discussion

### ISSUE THREAD

**Issue by glyph** [fantasylandinst/fcop#54]
"Don't Moralize" is presented as a requirement for participation in a community, but the FCOP itself defines a moral system (despite purporting to "not intended to impose any system of […] morals"); to wit, that stereotyping, denigration, harassment, prying, doxing, and shaming are moral ills, and civility is a moral good.

Since it is not possible to discuss the merits of the moral system outlined in the FCOP without violating this clause, I'll have to do so in this issue.

The moral system defined by the FCOP is fairly anemic by many common ethical standards. For example, it doesn't define a moral hierarchy, and doesn't prescribe or even suggest any guidelines for the selection of a sanction for a specific violation.

Other codes of conduct do not lay out a moral hierarchy or sentencing guidelines either, but they don't have this issue, because:

1. by avoiding banning discussion of morality, it's possible to have a subjective discussion about moral consequences among community leaders using their own existing moral and ethical systems,
2. they consistently describe behaviors that are generally considered similarly bad, i.e., different specific forms of harassment, rather than mixing "moralizing" (often considered a virtuous activity), "incivility" (a nebulously defined difference in tone) and "doxing" (an implicit threat of mob violence against someone) into the same list without distinguishing between them.

It seems like what this proscription on moralizing is aiming to do is to define a minimal-common-subset morality for professional interactions, and then prohibit unnecessary disagreement beyond that scope in the context that is covered by this document.  This is an admirable idea, in that it is a special case of finding ways to cooperate in some areas with people that one disagrees with in others, but it's also a phenomenally complex task.  The lack of any citation of prior art in other codes of conduct, or, for that matter, philosophy, game theory, or interfaith organizing, suggests that the authors many not have an appreciation of its scope.  I mention this mainly by way of saying that simply removing the proscription on moralizing won't resolve the other knock-on issues resulting from trying to erect a moral system, even one for a narrow context like "professional interactions", from first principles.

**Comment by jdegoes** [comment]
There is no statement in FCOP indicating its prescriptions on behavior are moral or immoral; it stipulates only that to participate in the community, one must behave as specified.

This is part of the terms and conditions of FCOP. Some may consider these prescriptions on behavior moral or not, as per their own religious, political, or moral systems, but such is beyond the scope of FCOP.

FCOP welcomes both those who believe these prescriptions are moral, those who believe these prescriptions are immoral, and those who believe these prescriptions are neither, but nonetheless, requires them to behave in accordance with these prescriptions, and prevents moralizing of these or any other prescriptions.

If you want to moralize people (be that convert them to Catholicism or shame them for not recycling enough), and you want to do so in the context of a professional community, I'd suggest FCOP will not serve those aims. There are other COCs that cater to such tastes.

**Comment by jdegoes** [comment]
Closed as not relevant to the goals of FCOP.

**Comment by glyph** [comment]
This seems to have been raised before in #49 for similar reasons; perhaps it is even a duplicate.

> There is no statement in FCOP indicating its prescriptions on behavior are moral or immoral; it stipulates only that to participate in the community, one must behave as specified.

You can talk about morality and still avoid the specific words "moral" or "immoral".  Your response here suggests that you may be ascribing a significantly more narrow definition to the word "moral" than is generally accepted.  Consulting wikipedia:

> Morality (from the Latin moralis "manner, character, proper behavior") is the differentiation of intentions, decisions, and actions between those that are distinguished as proper and those that are improper. Morality can be a body of standards or principles derived from a code of conduct from a particular philosophy, religion, or culture, or it can derive from a standard that a person believes should be universal. Morality may also be specifically synonymous with "goodness" or "rightness".

It sounds like you are trying to confine the word "morality" entirely to the latter sense here; however, that is not how the word is generally used, and you may need to circumscribe it more specifically.  I think what you're trying to prohibit is *proselytizing*, not moralizing.

**Comment by ankushnarula** [comment]
> It sounds like you are trying to confine the word "morality" entirely to the latter sense here; however, that is not how the word is generally used, and you may need to circumscribe it more specifically. I think what you're trying to prohibit is proselytizing, not moralizing.

Your point is taken but now we're talking about semantic preferences.  The word moralizing might be misconstrued as you suggest but the definition is plain as day:

As per the Oxford English Dictionary: 

[https://en.oxforddictionaries.com/definition/moralize](https://en.oxforddictionaries.com/definition/moralize)


> **moralize** (also moralise)
> VERB
> 1. (often as noun moralizing) [no object] Comment on issues of right and wrong, typically with an unfounded air of superiority.

**Comment by glyph** [comment]
Yes, to "comment on issues of right and wrong".  (Merriam-Webster is somewhat less pejorative in its recording of the connotations, but agrees on the denotation.)

Let's imagine an IBM technical conference in the 1930s.  It would explicitly be compliant with the FCOP to discuss optimizing the capabilities of their census software to categorize and annihilate Jews, but it would be a violation of the FCOP for someone to bring up the fact that this software was being used to commit mass murder, because rejection of mass murder involves "commenting on issues of right and wrong"?

**Comment by ankushnarula** [comment]
From what I gather (and mostly agree with), the real problem that the "No Moralizing" clause addresses is the "air of superiority" that comes with moralizing.  Sadly, in 2017, there are those who wish to politicize every facet of life in order to exercise this singular muscle and dominate others with their ideological orthodoxies.  The FCOP comprehensively codifies what until recently was considered common professional courtesy - "no religion and no politics" - and broadens it to include all ideological preferences.  

As for your scenario, I think your concern is that nobody would be allowed to speak-up at this imaginary technical conference - but I think that concern is unwarranted.  I'm not sure how @jdegoes views this, but from my perspective the spirit of "No Moralizing" does not preclude the community from raising and discussing professional ethical matters as they pertain to non-administrative content.  However, just as with technical matters, ethical matters must be discussed using empirical data/observation and questioned using scientific rigor.  The key here is that discussions would likely prohibit shows of moral superiority via dogmatic rhetoric, rhetorical anecdotes, and emotional pleas based on personal preferences.  (apply this to any technical/ethical flame war you can imagine)

**Comment by ankushnarula** [comment]
Just to reinforce my previous point please re-read the definition as described in the FCOP - I've pasted here for you:

> **Moralizing.** We define moralizing as an attempt to evangelize one's moral system to others, whether by communicating the idea that their moral system is superior, by denigrating the moral system of others, or by pressuring others to profess or practice their moral system.

**Comment by jdegoes** [comment]
As @ankushnarula says, there are ways of discussing these topics without moralizing—for example, emotivism's [methods of argumentation](https://en.wikipedia.org/wiki/Emotivism#Methods_of_argumentation) or the entirety of [non-violent communication](https://en.wikipedia.org/wiki/Nonviolent_Communication).

Realistic and modern examples might include:

 * Machine learning applied to recognition of human targets in the development of embedded software for armed drones;
 * Political analytics platforms that use deep learning to build complex psychological models of people for purposes of manipulating them into a chosen direction;
 * Development of scalable CMS infrastructure that powers some controversial website such as Breitbart or DailyMail;
 * Training networks to tweak game mechanics in freemium games so as to maximize user addiction to paid content.

And on and on.

In accordance with **No Victimless Violations**, individuals may, under mutual consent, engage in whatever heated battles they like about what is morally right or wrong. It's just the expectation is that, without such consent, every person leaves their politics, religion, and moral system at the door to better further the professional goals of the community. Nothing prevents them from discussing such issues in a non-moralizing way (see above), from discussing them in a moral way under mutual consent, or from discussing them outside the boundaries of the community.

**Comment by ankushnarula** [comment]
@jdegoes perhaps the FCOP needs to place a much heavier emphasis on mutual/group consent as it pertains to these types of discussions?  As it stands, folks are reading some of these points as  authoritative restrictions rather than negotiations between consenting members.

**Comment by jdegoes** [comment]
@ankushnarula Agreed. I think the "no victimless violations" can be re-written in terms of mutual / group consent, which will make me very happy, as the clause is vaguer than I'd like.
