### ISSUE TITLE
Rewrite no victimless violations as mutual / group consent

### ISSUE THREAD

**Issue by jdegoes** [fantasylandinst/fcop#55]

**Comment by ankushnarula** [comment]
I'm mulling it over but I think the "Behavior" section could use a point on mutual consent and group consensus.  In fact, that might be the first "Do" before iterating through the "Don'ts".

**Comment by jdegoes** [comment]
Yes, it could almost be a preface of sorts:

> We welcome a closed group of _members_ to engage in any behavior for which there is explicit and unanimous mutual consent. In the absence of this, we impose the following restrictions during active participation, which are further clarified in the glossary.
